### ISSUE TITLE
请问 运行黑屏，然后就崩溃了，是怎么回事？

### ISSUE THREAD

**Issue by ELEVENEV** [shenhuanet/OpenCV-android#1]
我试了安卓4.3  安卓5.1  安卓8.0 都是一运行就崩溃了，请问一下是怎么回事。

**Comment by ELEVENEV** [comment]
10-29 19:31:55.725 23479-23479/com.shenhua.opencv_android D/JavaCameraView: Preview Frame received. Frame size: 576000
10-29 19:31:55.745 23479-23983/com.shenhua.opencv_android E/cv::error(): OpenCV(3.4.1) Error: Assertion failed (src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols) in void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean), file /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp, line 101
10-29 19:31:55.745 23479-23983/com.shenhua.opencv_android E/org.opencv.android.Utils: nMatToBitmap caught cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:101: error: (-215) src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols in function void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean)
10-29 19:31:55.755 23479-23983/com.shenhua.opencv_android E/CameraBridge: Mat type: Mat [ 800*480*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0x55ad2c1bc0, dataAddr=0x7f80de1040 ]
    Bitmap type: 800*480
    Utils.matToBitmap() throws an exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:101: error: (-215) src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols in function void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean)
10-29 19:31:55.765 23479-23479/com.shenhua.opencv_android D/JavaCameraView: Preview Frame received. Frame size: 576000
10-29 19:31:55.795 23479-23983/com.shenhua.opencv_android E/cv::error(): OpenCV(3.4.1) Error: Assertion failed (src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols) in void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean), file /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp, line 101
10-29 19:31:55.795 23479-23983/com.shenhua.opencv_android E/org.opencv.android.Utils: nMatToBitmap caught cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:101: error: (-215) src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols in function void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean)
10-29 19:31:55.795 23479-23983/com.shenhua.opencv_android E/CameraBridge: Mat type: Mat [ 800*480*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0x55acf52650, dataAddr=0x7f80f59040 ]
    Bitmap type: 800*480
    Utils.matToBitmap() throws an exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:101: error: (-215) src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols in function void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean)
10-29 19:31:55.805 23479-23479/com.shenhua.opencv_android D/JavaCameraView: Preview Frame received. Frame size: 576000
10-29 19:31:55.825 23479-23983/com.shenhua.opencv_android E/cv::error(): OpenCV(3.4.1) Error: Assertion failed (src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols) in void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean), file /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp, line 101
10-29 19:31:55.825 23479-23983/com.shenhua.opencv_android E/org.opencv.android.Utils: nMatToBitmap caught cv::Exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:101: error: (-215) src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols in function void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean)
10-29 19:31:55.825 23479-23983/com.shenhua.opencv_android E/CameraBridge: Mat type: Mat [ 800*480*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0x55ad2c1bc0, dataAddr=0x7f80de1040 ]
    Bitmap type: 800*480
    Utils.matToBitmap() throws an exception: OpenCV(3.4.1) /build/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:101: error: (-215) src.dims == 2 && info.height == (uint32_t)src.rows && info.width == (uint32_t)src.cols in function void Java_org_opencv_android_Utils_nMatToBitmap2(JNIEnv*, jclass, jlong, jobject, jboolean)
10-29 19:31:55.855 23479-23479/com.shenhua.opencv_android D/JavaCameraView: Preview Frame received. Frame size: 576000

**Comment by jolinlinlin** [comment]
@ELEVENEV 你好，我出现了和你一样的问题，黑屏然后有上述错误提示，请问你解决这个问题了吗

**Comment by jolinlinlin** [comment]
@shenhuanet 请问你是怎么实现竖屏显示的，除了在程序中添加Core.transpose(mRgba, mRgba);Core.flip(mRgba, mRgba, 1)这两句之外，opencv库中的CameraBridgeViewBase文件修改了吗
